--CREATE OR REPLACE VIEW V_USW_P103_E_RAPOR_HEKIM AS
SELECT
         ER.ID AS DETAY_ID,
         K.TC_KIMLIK_NO AS HEKIM_KIMLIK_NUMARASI#Z
FROM FONETHBS.IS_GOREMEZLIK_RAPOR ER
INNER JOIN FONETHBS.HASTA_BIRIM_SEVK BS ON BS.ID = ER.BIRIM_SEVK_ID
INNER JOIN FONETHBS.PERSONEL P ON P.ID = BS.personel_id
INNER JOIN FONETHBS.KIMLIK K ON K.ID = P.KIMLIK_ID
WHERE ER.ETAR > '01.01.2015'
UNION ALL
SELECT
      ER.ID AS DETAY_ID,
      K.TC_KIMLIK_NO AS HEKIM_KIMLIK_NUMARASI
FROM FONETHBS.IS_GOREMEZLIK_RAPOR ER
INNER JOIN FONETHBS.HASTA_BIRIM_SEVK BS ON BS.ID = ER.BIRIM_SEVK_ID
INNER JOIN FONETHBS.IS_GOREMEZLIK_PERSONEL HYT ON HYT.RAPOR_ID =ER.ID
INNER JOIN FONETHBS.PERSONEL  P ON P.ID = HYT.PERSONEL_ID
INNER JOIN FONETHBS.KIMLIK K ON K.ID = P.KIMLIK_ID
WHERE ER.ETAR > '01.01.2015';
