CREATE OR REPLACE VIEW V_USW_P103_E_RAPOR AS
SELECT
        "BS"."HASTA_GELIS_ID" AS HK_ID,
        "ER"."ID" AS DETAY_ID,
        TO_CHAR("ER"."ETAR",'YYYYMMDDHH24MI') AS RAPOR_TARIHI#Z,
        "ER"."RAPOR_NO" AS RAPOR_NUMARASI#Z,
        DECODE("ER"."RAPOR_TURU",1,2,2,3,3,4,4,6,6,1,98) AS RAPOR_TURU#K,
        USS.GET_GUID_VALUE('3fb672ac-0675-44ef-9f91-86856dc79370',DECODE(ER.RAPOR_TURU,1,2,2,3,3,4,4,6,6,1,98)) AS RAPOR_TURU#A,
        '3fb672ac-0675-44ef-9f91-86856dc79370' RAPOR_TURU#C,
        TO_CHAR("ER"."BASLANGIC_TARIHI",'YYYYMMDDHH24MI') AS RAPOR_BASLANGIC_TARIHI#Z,
        TO_CHAR("ER"."BITIS_TARIHI",'YYYYMMDDHH24MI') AS RAPOR_BITIS_TARIHI#Z,
        TO_CHAR("ER"."RAPOR_TAKIP_NO") AS RAPOR_TAKIP_NUMARASI#Z,
        '' AS RAPOR_PDF_BILGISI#Z 
FROM "FONETHBS"."IS_GOREMEZLIK_RAPOR" /**/"ER"
INNER JOIN FONETHBS.HASTA_BIRIM_SEVK BS ON BS.ID = ER.BIRIM_SEVK_ID
WHERE ER.ETAR > '01.01.2015'
UNION ALL 
SELECT
        "BS"."HASTA_GELIS_ID" AS HK_ID,
        "ER"."ID" AS DETAY_ID,
        TO_CHAR("ER"."ETAR",'YYYYMMDDHH24MI') AS RAPOR_TARIHI#Z,
        "ER"."RAPOR_NO" AS RAPOR_NUMARASI#Z,
        DECODE("ER"."RAPOR_TURU",1,2,2,3,3,4,4,6,6,1,98) AS RAPOR_TURU#K,
        USS.GET_GUID_VALUE('3fb672ac-0675-44ef-9f91-86856dc79370',DECODE(ER.RAPOR_TURU,1,2,2,3,3,4,4,6,6,1,98)) AS RAPOR_TURU#A,
        '3fb672ac-0675-44ef-9f91-86856dc79370' RAPOR_TURU#C,
        TO_CHAR("ER"."BASLANGIC_TARIHI",'YYYYMMDDHH24MI') AS RAPOR_BASLANGIC_TARIHI#Z,
        TO_CHAR("ER"."BITIS_TARIHI",'YYYYMMDDHH24MI') AS RAPOR_BITIS_TARIHI#Z,
        TO_CHAR("ER"."RAPOR_TAKIP_NO") AS RAPOR_TAKIP_NUMARASI#Z,
        '' AS RAPOR_PDF_BILGISI#Z 
FROM FONETHBS.IS_GOREMEZLIK_RAPOR ER
INNER JOIN FONETHBS.HASTA_BIRIM_SEVK BS ON BS.ID = ER.BIRIM_SEVK_ID
INNER JOIN FONETHBS.HASTA_GELIS G ON BS.HASTA_GELIS_ID = G.ID
INNER JOIN FONETHBS.IS_GOREMEZLIK_PERSONEL HYT ON HYT.RAPOR_ID =ER.ID
INNER JOIN FONETHBS.PERSONEL  P ON P.ID = HYT.PERSONEL_ID
INNER JOIN FONETHBS.KIMLIK K ON K.ID = P.KIMLIK_ID
WHERE ER.ETAR > '01.01.2015';
