CREATE OR REPLACE VIEW V_USW_P101_HASTA_KIMLIK_BILGI AS
SELECT
        "HG"."ID" AS HK_ID,
        BS.HASTA_GELIS_ID AS DETAY_ID,
        NULL AS BABA_KIMLIK_NUMARASI,
        "K"."TC_KIMLIK_NO" AS HASTA_KIMLIK_NUMARASI#Z,
        "K"."ADI" AS AD#Z,
        "K"."SOYADI"AS SOYAD#Z,
        TO_CHAR(TO_DATE("K"."DOGUM_TARIHI"),'YYYYMMDD') AS DOGUM_TARIHI#Z,
        "K"."CINSIYET" AS CINSIYET#K,
        USS.GET_GUID_VALUE('784d0f4f-0603-4425-937f-1a3941fc3a1f',"K"."CINSIYET") AS CINSIYET#A#Z,
        '784d0f4f-0603-4425-937f-1a3941fc3a1f' AS CINSIYET#C,
        "U"."KODU"  AS UYRUK#K,
        USS.GET_GUID_VALUE('d650777a-3d4d-a259-e040-7c0a01167a83',U.KODU) AS UYRUK#A#Z,
        'd650777a-3d4d-a259-e040-7c0a01167a83' AS UYRUK#C,
        "H"."ANNE_TC_KIMLIK_NO" AS ANNE_KIMLIK_NUMARASI#Z,
        GK.BEBEK_SIRA_NO AS DOGUM_SIRASI#Z,
        NVL(GK.BEBEK_SIRA_NO,1) AS DOGUM_SIRASI#Z,
        NVL(DECODE(U.KODU,'TR', NULL,K.TC_KIMLIK_NO),'99999999999') AS YABANCI_HASTA_KIMLIK_NO#Z, --YABANCI_HASTA_KIMLIK_NUMARASI
        "K"."PASAPORT_NO" AS PASAPORT_NO#Z,
        NULL AS KIMLIKSIZ_HASTA_BILGISI#Z
FROM FONETHBS."HASTA_BIRIM_SEVK" BS 
INNER JOIN FONETHBS."HASTA_GELIS" HG ON HG.ID = BS.HASTA_GELIS_ID
INNER JOIN FONETHBS."HASTA" H ON H.ID = HG.HASTA_ID
INNER JOIN FONETHBS."KIMLIK" K ON K.ID = H.KIMLIK_ID
INNER JOIN FONETHBS."ADRES" AD ON AD.ID=K.ADRES_ID
LEFT JOIN FONETHBS."ULKE" U ON U.ID=K.ULKE_ID
LEFT JOIN FONETHBS."HASTA_GELIS_KABUL" GK ON GK.ID = HG.HASTA_GELIS_KABUL_ID
WHERE BS.SEVK_TARIHI > '01.01.2015';



CREATE OR REPLACE VIEW V_USW_P101_HASTA_KAYIT_ADRES AS
SELECT 
        BS.HASTA_GELIS_ID AS DETAY_ID,
        8 AS ADRES_KODU_SEVIYESI#K,
        USS.GET_GUID_VALUE('aa0e83ba-e9db-4817-80da-577fd6a17373',8) AS ADRES_KODU_SEVIYESI#A#Z,
        'aa0e83ba-e9db-4817-80da-577fd6a17373' AS ADRES_KODU_SEVIYESI#C,
        1 AS ADRES_KODU,
        "AD"."BEYAN_ADRES" AS ACIK_ADRES#Z,
        "AD"."ILCE_ADI" AS ACIK_ADRES_ILCE#Z
FROM FONETHBS."HASTA_BIRIM_SEVK" "BS"
INNER JOIN FONETHBS."HASTA_GELIS" HG ON HG.ID = BS.HASTA_GELIS_ID
INNER JOIN FONETHBS."HASTA" H ON H.ID = HG.HASTA_ID
INNER JOIN FONETHBS."KIMLIK" K ON K.ID = H.KIMLIK_ID
INNER JOIN FONETHBS."ADRES" AD ON AD.ID=K.ADRES_ID
LEFT JOIN FONETHBS."ULKE" U ON U.ID=K.ULKE_ID
LEFT JOIN FONETHBS."HASTA_GELIS_KABUL" GK ON GK.ID = HG.HASTA_GELIS_KABUL_ID
WHERE BS.SEVK_TARIHI > '01.01.2015';


CREATE OR REPLACE VIEW V_USW_P101_HASTA_BASVURU_BILGI AS
SELECT
        "HG"."ID" AS HK_ID,
        BS.ID AS DETAY_ID,
        NULL AS AMBULANS_TAKIP_NUMARASI,
        (SELECT X.DEGER FROM FONETHBS.PARAMETRE_DEGER X WHERE X.PARAMETRE_KEY = 'ENTEGRASYON3') AS HIZMET_SUNUCU#K,
        (SELECT XA.ADI FROM FONETHBS.USBS_KURUMLAR XA WHERE  XA.KODU IN (SELECT X.DEGER FROM FONETHBS.PARAMETRE_DEGER X WHERE X.PARAMETRE_KEY = 'ENTEGRASYON3')) AS HIZMET_SUNUCU#A#Z,
        'c3eade04-4f91-5dab-e043-14031b0ac9f9' AS HIZMET_SUNUCU#C,
        (SELECT X.DEGER FROM FONETHBS.PARAMETRE_DEGER X WHERE X.PARAMETRE_KEY = 'ENTEGRASYON3')  AS KAYIT_YERI#K,
        (SELECT XA.ADI FROM FONETHBS.USBS_KURUMLAR XA WHERE  XA.KODU IN (SELECT X.DEGER FROM FONETHBS.PARAMETRE_DEGER X WHERE X.PARAMETRE_KEY = 'ENTEGRASYON3')) AS KAYIT_YERI#A#Z,
        'c3eade04-4f91-5dab-e043-14031b0ac9f9' AS KAYIT_YERI#C,
        (SELECT NVL(MAX(DECODE(OP.PROTOKOL_NO,NULL,OP.KURUM_PROTOKOL_NO,OP.PROTOKOL_NO)),'-') FROM FONETHBS.ONLINE_PROTOKOL OP WHERE OP.POLIKLINIK_ID = POL.ID) AS PROTOKOL_NUMARASI#Z,
          HG.ID AS HK_ID,
          BS.TAKIP_NO AS SGK_TAKIP_NUMARASI#Z,
          TO_CHAR(POL.KABUL_TARIHI, 'YYYYMMDDHH24MI') AS KABUL_ZAMANI#Z,
          (select U.SKRS_KODU from FONETHBS.UZMANLIK U WHERE U.KODU IN (SELECT X.UZMANLIK_KODU FROM FONETHBS.BIRIM X WHERE X.ID = BS.BIRIM_ID)) AS KLINIK_KODU#K,
          USS.GET_GUID_VALUE('c04bee57-c5d4-443d-e040-7b0a6f146a3d',(select U.SKRS_KODU from FONETHBS.UZMANLIK U WHERE U.KODU IN (SELECT X.UZMANLIK_KODU FROM FONETHBS.BIRIM X WHERE X.ID = BS.BIRIM_ID))) AS KLINIK_KODU#A,
          'c04bee57-c5d4-443d-e040-7b0a6f146a3d' AS KLINIK_KODU#C,

              CASE WHEN (HS.SINIF_TURU IN (4,1)  AND NVL(HG.DEVREDILEN_KURUM,0) NOT IN (1,2,3) AND BS.TAKIP_NO IS NOT NULL)  THEN '30'
                   WHEN NVL(HG.DEVREDILEN_KURUM,0) IN (2) THEN '31'
                   WHEN NVL(HG.DEVREDILEN_KURUM,0) IN (1)  OR HS.SINIF_TURU IN (1) AND BS.TAKIP_NO IS NOT NULL    THEN '32'
                   WHEN NVL(HG.DEVREDILEN_KURUM,0)  IN (3) THEN '33'
                   WHEN HS.SINIF_TURU IN (5) THEN '35'
                   WHEN HS.SINIF_TURU IN (8) THEN '34'
                   WHEN HS.SINIF_TURU IN (2,3) THEN '97'
                   WHEN HS.SINIF_TURU IN (2,3,6,7,9,11) THEN '98'
                   WHEN HS.SINIF_TURU IS NULL THEN '99'
                   WHEN HS.SINIF_TURU IN (5) THEN '36'
                       ELSE '98' END AS SOSYAL_GUVENCE_DURUMU#K,
          USS.GET_GUID_VALUE('530da738-2be0-4adc-a7c1-aca18c66a3f8',( 
             CASE WHEN HS.SINIF_TURU IN (4,1)  AND NVL(HG.DEVREDILEN_KURUM,0) NOT IN (1,2,3) AND BS.TAKIP_NO IS NOT NULL  THEN '30'
                   WHEN NVL(HG.DEVREDILEN_KURUM,0) IN (2) THEN '31'
                   WHEN NVL(HG.DEVREDILEN_KURUM,0) IN (1)  AND HS.SINIF_TURU IN (1) AND BS.TAKIP_NO IS NOT NULL THEN '32'
                   WHEN NVL(HG.DEVREDILEN_KURUM,0)  IN (3) THEN '33'
                   WHEN HS.SINIF_TURU IN (5) THEN '35'
                   WHEN HS.SINIF_TURU IN (8) THEN '34'
                   WHEN HS.SINIF_TURU IN (2,3) THEN '97'
                   WHEN HS.SINIF_TURU IN (2,3,6,7,9,11) THEN '98'
                   WHEN HS.SINIF_TURU IS NULL THEN '99'
                   WHEN HS.SINIF_TURU IN (5) THEN '36'
             ELSE '98' END)) AS SOSYAL_GUVENCE_DURUMU#A#Z,
           '530da738-2be0-4adc-a7c1-aca18c66a3f8' AS SOSYAL_GUVENCE_DURUMU#C,
           DECODE(PK.TC_KIMLIK_NO, '99999999999',NULL,PK.TC_KIMLIK_NO) AS HEKIM_KIMLIK_NUMARASI#Z,
           DECODE(HG.VAKA_TURU ,1,1,2,4,3,2,4,3,5,5,6,6,8,2,13,8,16,2,17,4,1) AS VAKA_TURU#K,
           USS.GET_GUID_VALUE('46380e82-d8b1-407d-9554-255d95a9f959', DECODE(HG.VAKA_TURU ,1,1,2,4,3,2,4,3,5,5,6,6,8,2,13,8,16,2,17,4,1)) AS VAKA_TURU#A#Z,
           '46380e82-d8b1-407d-9554-255d95a9f959' AS VAKA_TURU#C,
           (SELECT MAX(MR.RANDEVU_HRN) FROM FONETHBS.MHRS_RANDEVU MR WHERE MR.KABUL_BIRIM_SEVK_ID = BS.ID) AS MHRS_RANDEVU_NUMARASI#Z,
           DECODE(HG.VAKA_TURU, '3', CASE WHEN (SELECT A.TRIAJ FROM FONETHBS.POLIKLINIK A WHERE A.BIRIM_SEVK_ID = BS.ID) IN (1,2,3) THEN (SELECT A.TRIAJ FROM FONETHBS.POLIKLINIK A WHERE A.BIRIM_SEVK_ID = BS.ID) ELSE 0 END, 0) AS TRIAJ#Z,
          USS.GET_SYSTAKIPNO(HG.ID) AS SYSTakipNo#Z
FROM "FONETHBS"."HASTA_BIRIM_SEVK"/**/"BS"
LEFT JOIN FONETHBS.POLIKLINIK POL ON POL.BIRIM_SEVK_ID= BS.ID
INNER JOIN FONETHBS.HASTA_GELIS HG ON HG.ID = BS.HASTA_GELIS_ID
LEFT JOIN FONETHBS.KIMLIK PK ON PK.ID = BS.PERSONEL_ID
LEFT JOIN FONETHBS.HASTA_SINIF HS ON HS.ID = HG.SINIF_ID
WHERE BS.SEVK_TARIHI > '01.01.2015' ;


CREATE OR REPLACE VIEW V_USW_P101_HASTA_KAYIT_YATIS AS
SELECT
      BS.ID AS DETAY_ID,
      TO_CHAR(KK.KABUL_TARIHI, 'YYYYMMDDHH24MI') AS YATIS_KABUL_ZAMANI#Z,
      (SELECT MAX(YT.YATAK_NO) FROM FONETHBS.KLINIK KL INNER JOIN FONETHBS.BIRIM_YATAK YT ON YT.ID = KL.YATAK_ID WHERE KL.KLINIK_KABUL_ID=KK.ID) AS YATAK_NO#Z,
      DECODE(NVL(POL.GUNUBIRLIK,0), 0, 0, 1)  AS YATIS_GUNUBIRLIK_MI#Z,
      (SELECT DECODE(B.GRUBU,1,1,99) FROM FONETHBS.BIRIM B WHERE B.ID= BS.BIRIM_ID) AS YATISIN_ACILIYETI#K,
      USS.GET_GUID_VALUE('dc6ff680-555f-44b2-855e-a47c51207e4f',(SELECT DECODE(B.GRUBU,1,1,99) FROM FONETHBS.BIRIM B WHERE B.ID= BS.BIRIM_ID)) AS YATISIN_ACILIYETI#A#Z,
      'dc6ff680-555f-44b2-855e-a47c51207e4f' AS YATISIN_ACILIYETI#C
FROM "FONETHBS"."HASTA_BIRIM_SEVK"/**/"BS"
INNER JOIN FONETHBS.POLIKLINIK POL ON POL.BIRIM_SEVK_ID= BS.ID
INNER JOIN FONETHBS.KLINIK_KABUL KK ON KK.BIRIM_SEVK_ID = POL.YATIS_BIRIM_SEVK_ID
INNER JOIN FONETHBS.HASTA_GELIS HG ON HG.ID = BS.HASTA_GELIS_ID
LEFT JOIN FONETHBS.KIMLIK PK ON PK.ID = BS.PERSONEL_ID
LEFT JOIN FONETHBS.HASTA_SINIF HS ON HS.ID = HG.SINIF_ID
WHERE BS.SEVK_TARIHI > '01.01.2015';

