SELECT
      BS.ID AS DETAY_ID,
      TO_CHAR(KK.KABUL_TARIHI, 'YYYYMMDDHH24MI') AS YATIS_KABUL_ZAMANI#Z,
      (SELECT MAX(YT.YATAK_NO) FROM FONETHBS.KLINIK KL INNER JOIN FONETHBS.BIRIM_YATAK YT ON YT.ID = KL.YATAK_ID WHERE KL.KLINIK_KABUL_ID=KK.ID) AS YATAK_NO#Z,
      DECODE(NVL(POL.GUNUBIRLIK,0), 0, 0, 1)  AS YATIS_GUNUBIRLIK_MI#Z,
      (SELECT DECODE(B.GRUBU,1,1,99) FROM FONETHBS.BIRIM B WHERE B.ID= BS.BIRIM_ID) AS YATISIN_ACILIYETI#K,
      USS.GET_GUID_VALUE('dc6ff680-555f-44b2-855e-a47c51207e4f',(SELECT DECODE(B.GRUBU,1,1,99) FROM FONETHBS.BIRIM B WHERE B.ID= BS.BIRIM_ID)) AS YATISIN_ACILIYETI#A#Z,
      'dc6ff680-555f-44b2-855e-a47c51207e4f' AS YATISIN_ACILIYETI#C
FROM "FONETHBS"."HASTA_BIRIM_SEVK"/**/"BS"
INNER JOIN FONETHBS.POLIKLINIK POL ON POL.BIRIM_SEVK_ID= BS.ID
INNER JOIN FONETHBS.KLINIK_KABUL KK ON KK.BIRIM_SEVK_ID = POL.YATIS_BIRIM_SEVK_ID
INNER JOIN FONETHBS.HASTA_GELIS HG ON HG.ID = BS.HASTA_GELIS_ID
LEFT JOIN FONETHBS.KIMLIK PK ON PK.ID = BS.PERSONEL_ID
LEFT JOIN FONETHBS.HASTA_SINIF HS ON HS.ID = HG.SINIF_ID
WHERE BS.SEVK_TARIHI > '01.01.2015'
