SELECT 
        BS.HASTA_GELIS_ID AS DETAY_ID,
        8 AS ADRES_KODU_SEVIYESI#K,
        USS.GET_GUID_VALUE('aa0e83ba-e9db-4817-80da-577fd6a17373',8) AS ADRES_KODU_SEVIYESI#A#Z,
        'aa0e83ba-e9db-4817-80da-577fd6a17373' AS ADRES_KODU_SEVIYESI#C,
        1 AS ADRES_KODU,
        "AD"."BEYAN_ADRES" AS ACIK_ADRES#Z,
        "AD"."ILCE_ADI" AS ACIK_ADRES_ILCE#Z
FROM FONETHBS."HASTA_BIRIM_SEVK" "BS"
INNER JOIN FONETHBS."HASTA_GELIS" HG ON HG.ID = BS.HASTA_GELIS_ID
INNER JOIN FONETHBS."HASTA" H ON H.ID = HG.HASTA_ID
INNER JOIN FONETHBS."KIMLIK" K ON K.ID = H.KIMLIK_ID
INNER JOIN FONETHBS."ADRES" AD ON AD.ID=K.ADRES_ID
LEFT JOIN FONETHBS."ULKE" U ON U.ID=K.ULKE_ID
LEFT JOIN FONETHBS."HASTA_GELIS_KABUL" GK ON GK.ID = HG.HASTA_GELIS_KABUL_ID
WHERE BS.SEVK_TARIHI > '01.01.2015';
