CREATE OR REPLACE VIEW V_USW_P102_HIZMET AS
SELECT
            "BS"."HASTA_GELIS_ID" AS HK_ID,
            "BS"."ID" AS DETAY_ID,
            (select U.SKRS_KODU from FONETHBS.UZMANLIK U WHERE U.KODU IN (SELECT X.UZMANLIK_KODU FROM FONETHBS.BIRIM X WHERE X.ID = BS.BIRIM_ID))  AS KLINIK_KODU#K,
            USS.GET_GUID_VALUE('c04bee57-c5d4-443d-e040-7b0a6f146a3d',(select U.SKRS_KODU from FONETHBS.UZMANLIK U WHERE U.KODU IN (SELECT X.UZMANLIK_KODU FROM FONETHBS.BIRIM X WHERE X.ID = BS.BIRIM_ID))) AS KLINIK_KODU#A#Z,
            'c04bee57-c5d4-443d-e040-7b0a6f146a3d' AS KLINIK_KODU#C,
            TO_CHAR(CASE WHEN "HH"."ONAY_TARIHI" IS NOT NULL THEN HH.ONAY_TARIHI ELSE HH.ETAR END,'YYYYMMDDHH24MI') AS GERCEKLESME_ZAMANI#Z,
            1 AS ISLEM_TURU#K,
            USS.GET_GUID_VALUE('d03e562d-252e-451f-9a80-98d48b47c2f2',1) AS ISLEM_TURU#A,
            'd03e562d-252e-451f-9a80-98d48b47c2f2' AS ISLEM_TURU#C,
            SUBSTR(REPLACE(HZ.SUT_RESMI_KODU,'.',''),1,6) AS ISLEM_KODU#Z,
            HZ.SUT_RESMI_ADI AS ISLEM_ADI#Z,
            SUBSTR(REPLACE(HZ.GIL_RESMI_KODU,'.',''),1,6) AS GIRISIMSEL_ISLEM_KODU#Z,
            TO_CHAR(GREATEST(HH.ISTEM_TARIHI, HH.ETAR),'YYYYMMDDHH24MI') AS ISLEM_ZAMANI#Z,
            "HH"."MIKTAR" AS ADET#Z,
            CASE WHEN   ROUND(DECODE("HH"."ODEME_TURU",2, HH.MIKTAR * "HH"."HIZMET_FIYAT"),2) <= 6000
                   THEN  ROUND(DECODE(HH.ODEME_TURU,2, HH.MIKTAR * HH.HIZMET_FIYAT),2)
                 WHEN  ROUND(DECODE(HH.ODEME_TURU,2, HH.MIKTAR * HH.HIZMET_FIYAT),2) >= 6000
                   THEN (CASE WHEN ROUND(HZ.SUT_FIYAT * HH.MIKTAR)>6000 THEN 0 ELSE ROUND(HZ.SUT_FIYAT * HH.MIKTAR) END )
                 ELSE 0 END  AS HASTA_TUTARI#Z,
            CASE WHEN   ROUND(DECODE(HH.ODEME_TURU,1, HH.MIKTAR * HH.HIZMET_FIYAT),2) <= 6000
                    THEN  ROUND(DECODE(HH.ODEME_TURU,1, HH.MIKTAR * HH.HIZMET_FIYAT),2)
                 WHEN  ROUND(DECODE(HH.ODEME_TURU,1, HH.MIKTAR * HH.HIZMET_FIYAT),2) > 6000
                    THEN (CASE WHEN ROUND(HZ.SUT_FIYAT * HH.MIKTAR)>6000 THEN 0 ELSE ROUND(HZ.SUT_FIYAT * HH.MIKTAR) END)
                 ELSE 0 END AS KURUM_TUTARI#Z,
            CASE WHEN SUBSTR (HZ.SUT_RESMI_KODU,1,1) LIKE '8%' AND B.UZMANLIK_KODU IN (4400) 
                     THEN NULL 
                 WHEN SUBSTR(HZ.SUT_RESMI_KODU,1,7)=('520.030')  
                     THEN TO_CHAR(TO_DATE(REPLACE(G.MURACAAT_TARIHI,'/','.')||' '||SUBSTR(G.MURACAAT_TARIHI,1,5),'DD.MM.YYYY HH24:MI'),'YYYYMMDDHH24MI') 
                 ELSE TO_CHAR(HH.ETAR,'YYYYMMDDHH24MI') 
                 END AS RANDEVU_ZAMANI#Z,
           (SELECT K.TC_KIMLIK_NO FROM FONETHBS.KIMLIK K INNER JOIN FONETHBS.KULLANICI KK ON KK.KIMLIK_ID = K.ID WHERE KK.ID = HH.EKUL) AS KULLANICI_KIMLIK_NUMARASI#Z,
            '' AS CIHAZ_NUMARASI#Z,
            HH.ID AS ISLEM_REFERANS_NUMARASI
FROM FONETHBS."HASTA_BIRIM_SEVK"/**/"BS"
INNER JOIN FONETHBS.HASTA_HIZMET HH ON HH.BIRIM_SEVK_ID = BS.ID
INNER JOIN FONETHBS.HIZMET_MAKRO M ON M.ID = HH.MAKRO_ID
INNER JOIN FONETHBS.HIZMET HZ ON HZ.ID = M.HIZMET_ID
INNER JOIN FONETHBS.HASTA_GELIS G ON G.ID = BS.HASTA_GELIS_ID
LEFT JOIN FONETHBS.BIRIM B ON B.ID = BS.BIRIM_ID
WHERE 1=1
AND G.MURACAAT_TARIHI >= '01.01.2015';




CREATE OR REPLACE VIEW V_USW_P102_ILAC AS
SELECT
          "CD"."ID" AS DETAY_ID,
          "G"."ID" AS HK_ID,
          (SELECT U.SKRS_KODU FROM FONETHBS.UZMANLIK U LEFT JOIN FONETHBS.BIRIM B ON B.UZMANLIK_KODU = U.KODU WHERE B.ID = BS.BIRIM_ID )AS KLINIK_KODU#K,
          USS.GET_GUID_VALUE('c04bee57-c5d4-443d-e040-7b0a6f146a3d',(SELECT U.SKRS_KODU FROM FONETHBS.UZMANLIK U LEFT JOIN FONETHBS.BIRIM B ON B.UZMANLIK_KODU = U.KODU WHERE B.ID = BS.BIRIM_ID )) AS KLINIK_KODU#A#Z,
          'c04bee57-c5d4-443d-e040-7b0a6f146a3d' AS KLINIK_KODU#C,
          TO_CHAR("CD"."ETAR", 'YYYYMMDDHH24MI') AS GERCEKLESME_ZAMANI#Z,
          DECODE(S.TURU,0,2,1,3) AS ISLEM_TURU#K,
          USS.GET_GUID_VALUE('d03e562d-252e-451f-9a80-98d48b47c2f2',DECODE(S.TURU,0,'2',1,'3')) AS ISLEM_TURU#A,
          'd03e562d-252e-451f-9a80-98d48b47c2f2' AS ISLEM_TURU#C,
          SUBSTR(REPLACE(S.BARKOD_NO,'.',''),1,6) AS ISLEM_KODU#Z,
          S.ADI AS ISLEM_ADI#Z,
          '' AS GIRISIMSEL_ISLEM_KODU#Z,
          TO_CHAR(CD.ETAR, 'YYYYMMDDHH24MI') AS ISLEM_ZAMANI#Z,
          "CD"."MIKTAR" AS ADET#Z,
          ROUND(DECODE("CD"."ODEME_TURU",'2', CD.MIKTAR * CD.FIYAT),2) AS HASTA_TUTARI#Z,
          ROUND(DECODE(CD.ODEME_TURU,'1', CD.MIKTAR * CD.FIYAT),2) AS KURUM_TUTARI#Z,
          TO_CHAR(CD.ETAR, 'YYYYMMDDHH24MI') AS RANDEVU_ZAMANI#Z,
          (SELECT K.TC_KIMLIK_NO FROM FONETHBS.KIMLIK K WHERE K.ID = KL.KIMLIK_ID) AS KULLANICI_KIMLIK_NUMARASI#Z,
          '' AS CIHAZ_NUMARASI#Z,
          CD.ID AS ISLEM_REFERANS_NUMARASI
FROM FONETHBS."STOK_CIKIS_DETAY"/**/"CD"
INNER JOIN FONETHBS.STOK S ON S.ID = "CD"."STOK_ID"
LEFT JOIN FONETHBS.KULLANICI KL ON KL.ID = "CD"."EKUL"
LEFT JOIN FONETHBS.HASTA_BIRIM_SEVK BS ON BS.ID="CD"."BIRIM_SEVK_ID"
LEFT JOIN FONETHBS.HASTA_GELIS G ON BS.HASTA_GELIS_ID = G.ID
WHERE "CD"."FORM_TYPE" IN (1,2)
AND S.TURU IN (0,1)
AND G.MURACAAT_TARIHI >= '01.01.2015'
AND CD.BIRIM_SEVK_ID > 0;




CREATE OR REPLACE VIEW V_USW_P102_HIZMET_PUAN AS
SELECT
T.ID AS DETAY_ID,
K.TC_KIMLIK_NO AS HEKIM_KIMLIK_NUMARASI#Z,
T.TOPLAMPUAN AS ISLEM_PUANI#Z,
TO_CHAR(T.TARIH, 'YYYYMMDD') || REPLACE(T.SAAT, ':', '') AS PUAN_HAKEDIS_ZAMANI#Z
FROM FONETHBS.V_IST2_EKPRIM_LISTKAYIT T
INNER JOIN FONETHBS.KIMLIK K ON K.ID = T.DOKTORID
WHERE T.ONAYDURUM = 1
AND USS.IS_VALID_TC_KIMLIK_NO(K.TC_KIMLIK_NO) = 1
AND T.TARIH >= '01.01.2015';





