SELECT
          "CD"."ID" AS DETAY_ID,
          "G"."ID" AS HK_ID,
          (SELECT U.SKRS_KODU FROM FONETHBS.UZMANLIK U LEFT JOIN FONETHBS.BIRIM B ON B.UZMANLIK_KODU = U.KODU WHERE B.ID = BS.BIRIM_ID )AS KLINIK_KODU#K,
          USS.GET_GUID_VALUE('c04bee57-c5d4-443d-e040-7b0a6f146a3d',(SELECT U.SKRS_KODU FROM FONETHBS.UZMANLIK U LEFT JOIN FONETHBS.BIRIM B ON B.UZMANLIK_KODU = U.KODU WHERE B.ID = BS.BIRIM_ID )) AS KLINIK_KODU#A#Z,
          'c04bee57-c5d4-443d-e040-7b0a6f146a3d' AS KLINIK_KODU#C,
          TO_CHAR("CD"."ETAR", 'YYYYMMDDHH24MI') AS GERCEKLESME_ZAMANI#Z,
          DECODE(S.TURU,0,2,1,3) AS ISLEM_TURU#K,
          USS.GET_GUID_VALUE('d03e562d-252e-451f-9a80-98d48b47c2f2',DECODE(S.TURU,0,'2',1,'3')) AS ISLEM_TURU#A,
          'd03e562d-252e-451f-9a80-98d48b47c2f2' AS ISLEM_TURU#C,
          SUBSTR(REPLACE(S.BARKOD_NO,'.',''),1,6) AS ISLEM_KODU#Z,
          S.ADI AS ISLEM_ADI#Z,
          '' AS GIRISIMSEL_ISLEM_KODU#Z,
          TO_CHAR(CD.ETAR, 'YYYYMMDDHH24MI') AS ISLEM_ZAMANI#Z,
          "CD"."MIKTAR" AS ADET#Z,
          ROUND(DECODE("CD"."ODEME_TURU",'2', CD.MIKTAR * CD.FIYAT),2) AS HASTA_TUTARI#Z,
          ROUND(DECODE(CD.ODEME_TURU,'1', CD.MIKTAR * CD.FIYAT),2) AS KURUM_TUTARI#Z,
          TO_CHAR(CD.ETAR, 'YYYYMMDDHH24MI') AS RANDEVU_ZAMANI#Z,
          (SELECT K.TC_KIMLIK_NO FROM FONETHBS.KIMLIK K WHERE K.ID = KL.KIMLIK_ID) AS KULLANICI_KIMLIK_NUMARASI#Z,
          '' AS CIHAZ_NUMARASI#Z,
          CD.ID AS ISLEM_REFERANS_NUMARASI
FROM FONETHBS."STOK_CIKIS_DETAY"/**/"CD"
INNER JOIN FONETHBS.STOK S ON S.ID = "CD"."STOK_ID"
LEFT JOIN FONETHBS.KULLANICI KL ON KL.ID = "CD"."EKUL"
LEFT JOIN FONETHBS.HASTA_BIRIM_SEVK BS ON BS.ID="CD"."BIRIM_SEVK_ID"
LEFT JOIN FONETHBS.HASTA_GELIS G ON BS.HASTA_GELIS_ID = G.ID
WHERE "CD"."FORM_TYPE" IN (1,2)
AND S.TURU IN (0,1)
AND G.MURACAAT_TARIHI >= '01.01.2015'
AND CD.BIRIM_SEVK_ID > 0;
