
CREATE OR REPLACE VIEW V_USW_P102_HIZMET_PUAN AS
SELECT
T.HIID AS DETAY_ID,
P.P_TCKIMLIK AS HEKIM_KIMLIK_NUMARASI#Z,
T.TOPLAMPUAN AS ISLEM_PUANI#Z,
TO_CHAR(T.TARIH, 'YYYYMMDD') || REPLACE(T.SAAT, ':', '') AS PUAN_HAKEDIS_ZAMANI#Z
FROM V_IST2_EKPRIM_LIST T
INNER JOIN FONETHBYSADM.H_PERSON P ON P.P_ID = T.DOKTORID
WHERE T.ONAYDURUM = 1
AND USS.IS_VALID_TC_KIMLIK_NO(P.P_TCKIMLIK) = 1
AND T.TARIH >= '01.01.2015';





