SELECT
T.ID AS DETAY_ID,
K.TC_KIMLIK_NO AS HEKIM_KIMLIK_NUMARASI#Z,
T.TOPLAMPUAN AS ISLEM_PUANI#Z,
TO_CHAR(T.TARIH, 'YYYYMMDD') || REPLACE(T.SAAT, ':', '') AS PUAN_HAKEDIS_ZAMANI#Z
FROM FONETHBS.V_IST2_EKPRIM_LISTKAYIT T
INNER JOIN FONETHBS.KIMLIK K ON K.ID = T.DOKTORID
WHERE T.ONAYDURUM = 1
AND USS.IS_VALID_TC_KIMLIK_NO(K.TC_KIMLIK_NO) = 1
AND T.TARIH >= '01.01.2015';
