CREATE OR REPLACE VIEW V_USW_P102_HIZMET AS
SELECT
"Y"."HI_ID" AS DETAY_ID,
"Y"."HI_KAYITID" AS HK_ID,
NVL((SELECT U.SKRSKODU FROM FONETHBYSADM.H_UZMKOD U WHERE U.ID=SR.SR_UZMKOD_ID),(SELECT U.SKRSKODU FROM FONETHBYSADM.H_UZMKOD U WHERE U.ID=SU.SR_UZMKOD_ID)) AS KLINIK_KODU#K,
USS.GET_GUID_VALUE('c04bee57-c5d4-443d-e040-7b0a6f146a3d',NVL((SELECT U.SKRSKODU FROM FONETHBYSADM.H_UZMKOD U WHERE U.ID=SR.SR_UZMKOD_ID),(SELECT U.SKRSKODU FROM FONETHBYSADM.H_UZMKOD U WHERE U.ID=SU.SR_UZMKOD_ID))) AS KLINIK_KODU#A#Z,
'c04bee57-c5d4-443d-e040-7b0a6f146a3d' AS KLINIK_KODU#C,
TO_CHAR(GREATEST(GREATEST("Y"."HI_EKLEMETARIHI", X.HK_EKLETARIHI), CASE WHEN "Y"."HI_ONAYTARIHI" IS NOT NULL THEN Y.HI_ONAYTARIHI WHEN "Y"."HI_BITSAAT" IS NOT NULL THEN TO_DATE(TO_CHAR("Y"."HI_EKLEMETARIHI") ||' '|| Y.HI_BITSAAT, 'DD.MM.YYYY HH24:MI') ELSE Y.HI_EKLEMETARIHI END),'YYYYMMDDHH24MI') AS GERCEKLESME_ZAMANI#Z,
1 AS ISLEM_TURU#K,
USS.GET_GUID_VALUE('d03e562d-252e-451f-9a80-98d48b47c2f2',1) AS ISLEM_TURU#A,
'd03e562d-252e-451f-9a80-98d48b47c2f2' AS ISLEM_TURU#C,
SUBSTR(REPLACE(I.IS_RESMIKOD,'.',''),1,6) AS ISLEM_KODU#Z,
I.IS_ADI AS ISLEM_ADI#Z,
SUBSTR(REPLACE(I.GIL_RESMIKOD,'.',''),1,6) AS GIRISIMSEL_ISLEM_KODU#Z,
TO_CHAR(GREATEST(Y.HI_EKLEMETARIHI, X.HK_EKLETARIHI),'YYYYMMDDHH24MI') AS ISLEM_ZAMANI#Z,
"Y"."HI_MIKTAR" AS ADET#Z,
CASE WHEN   ROUND(DECODE("Y"."HI_ODTURU",'Ücretli', Y.HI_MIKTAR * "Y"."HI_FIYAT_YTL"),2) <= 6000
        THEN  ROUND(DECODE(Y.HI_ODTURU,'Ücretli', Y.HI_MIKTAR * Y.HI_FIYAT_YTL),2)
          WHEN  ROUND(DECODE(Y.HI_ODTURU,'Ücretli', Y.HI_MIKTAR * Y.HI_FIYAT_YTL),2) >= 6000
            THEN (SELECT CASE WHEN ROUND(I.IS_UCRET_YTL*Y.HI_MIKTAR)>6000 THEN 0 ELSE ROUND(I.IS_UCRET_YTL*Y.HI_MIKTAR) END   FROM H_ISLEM  I WHERE I.IS_ID = Y.HI_ISLEMID)
              ELSE 0 END  AS HASTA_TUTARI#Z,
CASE WHEN   ROUND(DECODE(Y.HI_ODTURU,'Sevkli', Y.HI_MIKTAR * Y.HI_FIYAT_YTL),2) <= 6000
        THEN  ROUND(DECODE(Y.HI_ODTURU,'Sevkli', Y.HI_MIKTAR * Y.HI_FIYAT_YTL),2)
          WHEN  ROUND(DECODE(Y.HI_ODTURU,'Sevkli', Y.HI_MIKTAR * Y.HI_FIYAT_YTL),2) > 6000
            THEN (SELECT CASE WHEN ROUND(I.IS_UCRET_YTL*Y.HI_MIKTAR)>6000 THEN 0 ELSE ROUND(I.IS_UCRET_YTL*Y.HI_MIKTAR) END  FROM H_ISLEM  I WHERE I.IS_ID = Y.HI_ISLEMID)
              ELSE 0 END AS KURUM_TUTARI#Z,
CASE WHEN SUBSTR (I.IS_RESMIKOD,1,1) LIKE '8%' AND SU.SR_UZMKOD_ID IN (SELECT ID FROM FONETHBYSADM.H_UZMKOD WHERE KOD IN (4400)) THEN NULL WHEN SUBSTR(I.IS_RESMIKOD,1,7)=('520.030')  THEN TO_CHAR(TO_DATE(REPLACE(X.HK_MURACAATTAR,'/','.')||' '||SUBSTR(X.HK_HASGELSAAT,1,5),'DD.MM.YYYY HH24:MI'),'YYYYMMDDHH24MI') ELSE TO_CHAR(Y.HI_EKLEMETARIHI,'YYYYMMDDHH24MI') END AS RANDEVU_ZAMANI#Z,
K.TCKIMLIKNO AS KULLANICI_KIMLIK_NUMARASI#Z,
'' AS CIHAZ_NUMARASI#Z,
Y.HI_ID AS ISLEM_REFERANS_NUMARASI
FROM "H_HASTAKAYIT_ALT"/**/"Y"
INNER JOIN H_ISLEM I ON I.IS_ID=Y.HI_ISLEMID
INNER JOIN H_HASTAKAYIT X ON X.HK_ID=Y.HI_KAYITID
INNER JOIN FONETHBYSADM.YTK_KULLANICI K ON K.ID="Y"."HI_EKLEYEN"
LEFT JOIN FONETHBYSADM.H_SERVIS SR ON SR.SR_ID="Y"."HI_SERVISID"
LEFT JOIN FONETHBYSADM.H_SERVIS SU ON SU.SR_ID="Y"."HI_SERVISIDUST"
WHERE NVL(Y.HI_EMAKROKOD,'-') <> '+'
AND X.HK_MURACAATTAR >= '01.01.2015'
--AND X.HK_MUAYENE='E'
AND NVL(Y.HI_SERVISID,Y.HI_SERVISIDUST) > 0;




