SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR1
WHERE NVL(KD.DOKTOR1,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR2
WHERE NVL(KD.DOKTOR2,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR3
WHERE NVL(KD.DOKTOR3,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR4
WHERE NVL(KD.DOKTOR4,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR5
WHERE NVL(KD.DOKTOR5,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR6
WHERE NVL(KD.DOKTOR6,-1) >0 
UNION ALL
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR7
WHERE NVL(KD.DOKTOR7,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR8
WHERE NVL(KD.DOKTOR8,-1) >0
