--CREATE OR REPLACE VIEW V_USS_P253_RAPOR_DETAY AS
SELECT "RK"."HKID" AS HK_ID,
       "RK"."ID" AS DETAY_ID,
       "RK"."TARIH" AS RAPOR_TARIHI,
       "RK"."RAPORNO" AS RAPOR_NUMARASI,
       USS.GET_KODU('3fb672ac-0675-44ef-9f91-86856dc79370',14) AS RAPOR_TURU#K,
       USS.GET_GUID_VALUE('3fb672ac-0675-44ef-9f91-86856dc79370',14) AS RAPOR_TURU#A,
       '3fb672ac-0675-44ef-9f91-86856dc79370' AS RAPOR_TURU#C,
       TO_CHAR("RK"."TARIH",'YYYYMMDDHH24MI')  AS RAPOR_BASLANGIC_TARIHI,
       TO_CHAR("RK"."TARIH",'YYYYMMDDHH24MI')  AS RAPOR_BITIS_TARIHI,
       RK.KONTROLSURETIPI,RK.KONTROLSUREDIGER
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4

/
--CREATE OR REPLACE VIEW V_USS_P253_RAPOR_HEKIM AS
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR1
WHERE NVL(KD.DOKTOR1,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR2
WHERE NVL(KD.DOKTOR2,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR3
WHERE NVL(KD.DOKTOR3,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR4
WHERE NVL(KD.DOKTOR4,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR5
WHERE NVL(KD.DOKTOR5,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR6
WHERE NVL(KD.DOKTOR6,-1) >0 
UNION ALL
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR7
WHERE NVL(KD.DOKTOR7,-1) >0 
UNION ALL 
SELECT "RK"."ID" AS DETAY_ID,
       "P"."P_TCKIMLIK" AS HEKIM_KIMLIK_NUMARASI
FROM SKR_KAYIT RK
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = RK.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN SKR_KAYITDOKTOR KD  ON KD.KAYITID = RK.ID
LEFT JOIN FONETHBYSADM.H_PERSON P ON P.P_ID= KD.DOKTOR8
WHERE NVL(KD.DOKTOR8,-1) >0
/
--CREATE OR REPLACE VIEW V_USS_P253_RAPOR_SURUCU AS
SELECT "K"."ID" AS DETAY_ID,
       "H"."HK_DOGUMTAR" AS DOGUM_TARIHI,
       "H"."HK_BABAADI" AS BABA_ADI,
       "H"."HK_ANAADI" AS ANNE_ADI,
       USS.GET_KODU('a3d6e943-5d85-4c75-ac72-709115974fb7',"HT"."HT_KANGRUBU") AS KAN_GRUBU#K, --GU?D VALUE DE?ER? BOS SONUC DONDURUYOR"."
       USS.GET_GUID_VALUE('a3d6e943-5d85-4c75-ac72-709115974fb7',"HT"."HT_KANGRUBU") AS KAN_GRUBU#A,
       'a3d6e943-5d85-4c75-ac72-709115974fb7' AS KAN_GRUBU#C,
--       USS.GET_KODU('59f0df45-3c03-4e40-b005-a151fd1d5411',null) AS RAPOR_MUAYENE_SONUCU#K, -- SKRS KAYIT BULUNMUYOR
--       USS.GET_GUID_VALUE('59f0df45-3c03-4e40-b005-a151fd1d5411',null) AS RAPOR_MUAYENE_SONUCU#A,
--       '59f0df45-3c03-4e40-b005-a151fd1d5411' AS RAPOR_MUAYENE_SONUCU#C,
   
       USS.GET_KODU('47b24d22-2a4b-4092-aa0c-d7216f729100',DECODE(nvl(E.KOD_ID,0),1,1,3,2,4,3,2,4,null)) AS KISIT_KODU#K,
       USS.GET_GUID_VALUE('47b24d22-2a4b-4092-aa0c-d7216f729100',DECODE(nvl(E.KOD_ID,0),1,1,3,2,4,3,2,4,null)) AS KISIT_KODU#A,
       '47b24d22-2a4b-4092-aa0c-d7216f729100' AS KISIT_KODU#C
FROM "SKR_KAYIT" "K"
LEFT JOIN SKR_EHLIYET E ON E.KAYITID =K.ID
INNER JOIN FONETHBYSADM.SKR_RAPORTANIM RT ON RT.ID = K.RAPORTURID AND RT.RAPORGRUBU = 4
INNER JOIN H_HASTAKAYIT H ON H.HK_ID = K.HKID
INNER JOIN FONETHBYSADM.H_HASTAT HT ON HT.HT_ID = H.HK_HASDOSYAID;
